// Code generated by MockGen. DO NOT EDIT.
// Source: app_request_network_test_helper.go
//
// Generated by this command:
//
//	mockgen -source=app_request_network_test_helper.go -destination=./mocks/mock_app_request_network.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ids "github.com/ava-labs/avalanchego/ids"
	message "github.com/ava-labs/avalanchego/message"
	subnets "github.com/ava-labs/avalanchego/subnets"
	set "github.com/ava-labs/avalanchego/utils/set"
	peers "github.com/ava-labs/icm-services/peers"
	gomock "go.uber.org/mock/gomock"
)

// MockAppRequestNetworkTestHelper is a mock of AppRequestNetworkTestHelper interface.
type MockAppRequestNetworkTestHelper struct {
	ctrl     *gomock.Controller
	recorder *MockAppRequestNetworkTestHelperMockRecorder
	isgomock struct{}
}

// MockAppRequestNetworkTestHelperMockRecorder is the mock recorder for MockAppRequestNetworkTestHelper.
type MockAppRequestNetworkTestHelperMockRecorder struct {
	mock *MockAppRequestNetworkTestHelper
}

// NewMockAppRequestNetworkTestHelper creates a new mock instance.
func NewMockAppRequestNetworkTestHelper(ctrl *gomock.Controller) *MockAppRequestNetworkTestHelper {
	mock := &MockAppRequestNetworkTestHelper{ctrl: ctrl}
	mock.recorder = &MockAppRequestNetworkTestHelperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppRequestNetworkTestHelper) EXPECT() *MockAppRequestNetworkTestHelperMockRecorder {
	return m.recorder
}

// GetCanonicalValidators mocks base method.
func (m *MockAppRequestNetworkTestHelper) GetCanonicalValidators(ctx context.Context, subnetID ids.ID, skipCache bool, pchainHeight uint64) (*peers.CanonicalValidators, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCanonicalValidators", ctx, subnetID, skipCache, pchainHeight)
	ret0, _ := ret[0].(*peers.CanonicalValidators)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCanonicalValidators indicates an expected call of GetCanonicalValidators.
func (mr *MockAppRequestNetworkTestHelperMockRecorder) GetCanonicalValidators(ctx, subnetID, skipCache, pchainHeight any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCanonicalValidators", reflect.TypeOf((*MockAppRequestNetworkTestHelper)(nil).GetCanonicalValidators), ctx, subnetID, skipCache, pchainHeight)
}

// GetSubnetID mocks base method.
func (m *MockAppRequestNetworkTestHelper) GetSubnetID(ctx context.Context, blockchainID ids.ID) (ids.ID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubnetID", ctx, blockchainID)
	ret0, _ := ret[0].(ids.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubnetID indicates an expected call of GetSubnetID.
func (mr *MockAppRequestNetworkTestHelperMockRecorder) GetSubnetID(ctx, blockchainID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubnetID", reflect.TypeOf((*MockAppRequestNetworkTestHelper)(nil).GetSubnetID), ctx, blockchainID)
}

// RegisterAppRequest mocks base method.
func (m *MockAppRequestNetworkTestHelper) RegisterAppRequest(requestID ids.RequestID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterAppRequest", requestID)
}

// RegisterAppRequest indicates an expected call of RegisterAppRequest.
func (mr *MockAppRequestNetworkTestHelperMockRecorder) RegisterAppRequest(requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterAppRequest", reflect.TypeOf((*MockAppRequestNetworkTestHelper)(nil).RegisterAppRequest), requestID)
}

// RegisterRequestID mocks base method.
func (m *MockAppRequestNetworkTestHelper) RegisterRequestID(requestID uint32, requestedNodes set.Set[ids.NodeID]) chan message.InboundMessage {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterRequestID", requestID, requestedNodes)
	ret0, _ := ret[0].(chan message.InboundMessage)
	return ret0
}

// RegisterRequestID indicates an expected call of RegisterRequestID.
func (mr *MockAppRequestNetworkTestHelperMockRecorder) RegisterRequestID(requestID, requestedNodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterRequestID", reflect.TypeOf((*MockAppRequestNetworkTestHelper)(nil).RegisterRequestID), requestID, requestedNodes)
}

// Send mocks base method.
func (m *MockAppRequestNetworkTestHelper) Send(msg message.OutboundMessage, nodeIDs set.Set[ids.NodeID], subnetID ids.ID, allower subnets.Allower) set.Set[ids.NodeID] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", msg, nodeIDs, subnetID, allower)
	ret0, _ := ret[0].(set.Set[ids.NodeID])
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockAppRequestNetworkTestHelperMockRecorder) Send(msg, nodeIDs, subnetID, allower any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockAppRequestNetworkTestHelper)(nil).Send), msg, nodeIDs, subnetID, allower)
}

// TrackSubnet mocks base method.
func (m *MockAppRequestNetworkTestHelper) TrackSubnet(ctx context.Context, subnetID ids.ID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TrackSubnet", ctx, subnetID)
}

// TrackSubnet indicates an expected call of TrackSubnet.
func (mr *MockAppRequestNetworkTestHelperMockRecorder) TrackSubnet(ctx, subnetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackSubnet", reflect.TypeOf((*MockAppRequestNetworkTestHelper)(nil).TrackSubnet), ctx, subnetID)
}
