// Code generated by icm-macros. DO NOT EDIT.
// Source: icm-contracts/common/ICM.sol
// To regenerate: ./scripts/expand_macros.sh

// (c) 2026, Ava Labs, Inc. All rights reserved.
// See the file LICENSE for licensing terms.
// SPDX-License-Identifier: LicenseRef-Ecosystem
pragma solidity ^0.8.30;

/**
 * THIS IS LIBRARY IS UN-AUDITED CODE.
 * DO NOT USE THIS CODE IN PRODUCTION.
 */

// #[pack(contract="ICM", name="serializeICMMessage")]
// #[unpack(contract="ICM", calldata, name="parseICMMessage")]
struct ICMMessage {
    // The serialized bytes of raw message. The data and serializations formats
    // for this data will be app / contract specific
    bytes rawMessage;
    // used to distinguish between mainnet and testnets
    uint32 sourceNetworkID;
    // The blockchain on which the message originated
    bytes32 sourceBlockchainID;
    // Arbitrary bytes that is used by receiving contracts to
    // authenticate this message.
    bytes attestation;
}

/**
 * @title ICM
 * @notice Utility library for Interchain Messaging (ICM) messages. Mainly (de)serialization.
 */
library ICM {
    function serializeICMMessage(ICMMessage memory obj) public pure returns (bytes memory) {
        /* solhint-disable */

        return abi.encodePacked(
            abi.encodePacked(obj.rawMessage.length, obj.rawMessage),
            abi.encodePacked(obj.sourceNetworkID),
            abi.encodePacked(obj.sourceBlockchainID),
            abi.encodePacked(obj.attestation.length, obj.attestation)
        );
        /* solhint-enable */
    }

    function parseICMMessage(bytes calldata data) public pure returns (uint256, ICMMessage memory) {
        /* solhint-disable */
        uint256 _initial_length = data.length;
        ICMMessage memory result;

        bytes memory rawMessage;
        {
            uint256 length = uint256(bytes32(data[0:32]));
            rawMessage = bytes(data[32:length + 32]);
            data = data[32 + length:];
        }
        result.rawMessage = rawMessage;
        uint32 sourceNetworkID = uint32(bytes4(data[0:4]));
        data = data[4:];
        result.sourceNetworkID = sourceNetworkID;
        bytes32 sourceBlockchainID = bytes32(data[0:32]);
        data = data[32:];
        result.sourceBlockchainID = sourceBlockchainID;
        bytes memory attestation;
        {
            uint256 length = uint256(bytes32(data[0:32]));
            attestation = bytes(data[32:length + 32]);
            data = data[32 + length:];
        }
        result.attestation = attestation;

        return (_initial_length - data.length, result);
        /* solhint-enable */
    }
}

