// Code generated by icm-macros. DO NOT EDIT.
// Source: icm-contracts/common/TeleporterMessageV2.sol
// To regenerate: ./scripts/expand_macros.sh

// (c) 2026, Ava Labs, Inc. All rights reserved.
// See the file LICENSE for licensing terms.

// SPDX-License-Identifier: LicenseRef-Ecosystem
pragma solidity 0.8.30;

import {TeleporterMessageReceipt} from "@teleporter/ITeleporterMessenger.sol";

/**
 * THIS IS AN EXAMPLE CONTRACT THAT USES UN-AUDITED CODE.
 * DO NOT USE THIS CODE IN PRODUCTION.
 */

// #[pack(contract="TeleporterV2Parsing", visibility="internal")]
// #[unpack(contract="TeleporterV2Parsing", visibility="internal", calldata)]
struct TeleporterMessageV2 {
    uint256 messageNonce;
    address originSenderAddress;
    // This is needed because we have an extra level of abstraction now. Before TeleporterMessenger was calling
    // WarpMessenger directly, so the `senderAddress` of the warp message was the address of the TeleporterMessenger contract.
    // Now, WarpAdapter is calling WarpMessenger, so the `originSenderAddress` of the warp message is the address of the WarpAdapter contract.
    address originTeleporterAddress;
    bytes32 destinationBlockchainID;
    address destinationAddress;
    uint256 requiredGasLimit;
    address[] allowedRelayerAddresses;
    // #[pack(method="serializeTeleporterReceipts")]
    // #[unpack(method="parseTeleporterReceipts")]
    TeleporterMessageReceipt[] receipts;
    bytes message;
}

// A domain type for the specific kind of ICM message TeleporterV2 expects
// #[pack(contract="TeleporterV2Parsing", visibility="internal")]
// #[unpack(contract="TeleporterV2Parsing", visibility="internal", calldata)]
struct TeleporterICMMessage {
    TeleporterMessageV2 message;
    // used to distinguish between mainnet and testnets
    uint32 sourceNetworkID;
    // The blockchain on which the message originated
    bytes32 sourceBlockchainID;
    // Arbitrary bytes that is used by receiving contracts to
    // authenticate this message.
    bytes attestation;
}

/**
 * @title ICMTeleporterV2
 * @notice Utility library for making TeleporterV2 work with ICM messages. Mainly (de)serialization
 */
library ICMTeleporterV2 {
    function parseTeleporterMessageV2(bytes calldata data) public pure returns (TeleporterMessageV2 memory) {
        (, TeleporterMessageV2 memory result) = TeleporterV2Parsing.unpackTeleporterMessageV2(data);
        return result;
    }

    function parseTeleporterICMMessage(bytes calldata message) public pure returns (TeleporterICMMessage memory) {
        (, TeleporterICMMessage memory result) = TeleporterV2Parsing.unpackTeleporterICMMessage(message);
        return result;
    }
}

library TeleporterV2Parsing {
    /**
     * @notice Parse a serialized array  of `TeleporterMessageReceipt` instances
     */
    function parseTeleporterReceipts(bytes calldata data)
        public
        pure
        returns (uint256, TeleporterMessageReceipt[] memory)
    {
        // get the number of receipts
        uint32 numReceipts = uint32(bytes4(data[:4]));
        TeleporterMessageReceipt[] memory receipts = new TeleporterMessageReceipt[](numReceipts);
        uint256 offsetReceipts = 4;
        // parse the receipts
        for (uint256 i = 0; i < numReceipts;) {
            receipts[i] = TeleporterMessageReceipt({
                receivedMessageNonce: uint256(bytes32(data[offsetReceipts:offsetReceipts + 32])),
                relayerRewardAddress: address(bytes20(data[offsetReceipts + 32:offsetReceipts + 52]))
            });
            offsetReceipts += 52;
            unchecked {
                i++;
            }
        }
        return (offsetReceipts, receipts);
    }

    /**
     * @notice serialize an array of `TeleporterMessageReceipt` instances
     */
    function serializeTeleporterReceipts(TeleporterMessageReceipt[] memory receipts)
        public
        pure
        returns (bytes memory)
    {
        bytes memory serialized = new bytes(receipts.length * 52);
        uint256 length = receipts.length;

        /* solhint-disable no-inline-assembly */
        assembly ("memory-safe") {
            let s := add(serialized, 0x20)
            let r := add(receipts, 0x20)
            for { let i := 0 } lt(i, length) { i := add(i, 1) } {
                // get the value at index number i
                let value := mload(r)
                mstore(s, mload(value))
                s := add(s, 32)
                // shift the address left 12 bytes
                mstore(s, shl(96, mload(add(value, 0x20))))
                s := add(s, 20)
                r := add(r, 32)
            }
        }
        /* solhint-enable no-inline-assembly */
        return abi.encodePacked(uint32(receipts.length), serialized);
    }

    function packTeleporterMessageV2(TeleporterMessageV2 memory obj) internal pure returns (bytes memory) {
        /* solhint-disable */
        bytes memory allowedRelayerAddresses_bytes;
        allowedRelayerAddresses_bytes = abi.encodePacked(obj.allowedRelayerAddresses.length);
        for (uint256 i_0 = 0; i_0 < obj.allowedRelayerAddresses.length;) {
            bytes memory allowedRelayerAddresses_1_bytes;
            allowedRelayerAddresses_1_bytes = abi.encodePacked(obj.allowedRelayerAddresses[i_0]);
            allowedRelayerAddresses_bytes =
                abi.encodePacked(allowedRelayerAddresses_bytes, allowedRelayerAddresses_1_bytes);
            unchecked {
                ++i_0;
            }
        }
        return abi.encodePacked(
            abi.encodePacked(obj.messageNonce),
            abi.encodePacked(obj.originSenderAddress),
            abi.encodePacked(obj.originTeleporterAddress),
            abi.encodePacked(obj.destinationBlockchainID),
            abi.encodePacked(obj.destinationAddress),
            abi.encodePacked(obj.requiredGasLimit),
            allowedRelayerAddresses_bytes,
            serializeTeleporterReceipts(obj.receipts),
            abi.encodePacked(obj.message.length, obj.message)
        );
        /* solhint-enable */
    }

    function packTeleporterICMMessage(TeleporterICMMessage memory obj) internal pure returns (bytes memory) {
        /* solhint-disable */

        return abi.encodePacked(
            packTeleporterMessageV2(obj.message),
            abi.encodePacked(obj.sourceNetworkID),
            abi.encodePacked(obj.sourceBlockchainID),
            abi.encodePacked(obj.attestation.length, obj.attestation)
        );
        /* solhint-enable */
    }

    function unpackTeleporterMessageV2(bytes calldata data)
        internal
        pure
        returns (uint256, TeleporterMessageV2 memory)
    {
        /* solhint-disable */
        uint256 _initial_length = data.length;
        TeleporterMessageV2 memory result;

        uint256 messageNonce = uint256(bytes32(data[0:32]));
        data = data[32:];
        result.messageNonce = messageNonce;
        address originSenderAddress = address(bytes20(data[0:20]));
        data = data[20:];
        result.originSenderAddress = originSenderAddress;
        address originTeleporterAddress = address(bytes20(data[0:20]));
        data = data[20:];
        result.originTeleporterAddress = originTeleporterAddress;
        bytes32 destinationBlockchainID = bytes32(data[0:32]);
        data = data[32:];
        result.destinationBlockchainID = destinationBlockchainID;
        address destinationAddress = address(bytes20(data[0:20]));
        data = data[20:];
        result.destinationAddress = destinationAddress;
        uint256 requiredGasLimit = uint256(bytes32(data[0:32]));
        data = data[32:];
        result.requiredGasLimit = requiredGasLimit;
        address[] memory allowedRelayerAddresses;
        {
            uint256 length = uint256(bytes32(data[0:32]));
            data = data[32:];
            allowedRelayerAddresses = new address[](length);
            for (uint256 i = 0; i < length;) {
                address allowedRelayerAddresses_1 = address(bytes20(data[0:20]));
                data = data[20:];
                allowedRelayerAddresses[i] = allowedRelayerAddresses_1;
                unchecked {
                    ++i;
                }
            }
        }
        result.allowedRelayerAddresses = allowedRelayerAddresses;
        TeleporterMessageReceipt[] memory receipts;
        {
            uint256 read;
            (read, receipts) = parseTeleporterReceipts(data);
            data = data[read:];
        }
        result.receipts = receipts;
        bytes memory message;
        {
            uint256 length = uint256(bytes32(data[0:32]));
            message = bytes(data[32:length + 32]);
            data = data[32 + length:];
        }
        result.message = message;

        return (_initial_length - data.length, result);
        /* solhint-enable */
    }

    function unpackTeleporterICMMessage(bytes calldata data)
        internal
        pure
        returns (uint256, TeleporterICMMessage memory)
    {
        /* solhint-disable */
        uint256 _initial_length = data.length;
        TeleporterICMMessage memory result;

        TeleporterMessageV2 memory message;
        {
            uint256 read;
            (read, message) = unpackTeleporterMessageV2(data);
            data = data[read:];
        }
        result.message = message;
        uint32 sourceNetworkID = uint32(bytes4(data[0:4]));
        data = data[4:];
        result.sourceNetworkID = sourceNetworkID;
        bytes32 sourceBlockchainID = bytes32(data[0:32]);
        data = data[32:];
        result.sourceBlockchainID = sourceBlockchainID;
        bytes memory attestation;
        {
            uint256 length = uint256(bytes32(data[0:32]));
            attestation = bytes(data[32:length + 32]);
            data = data[32 + length:];
        }
        result.attestation = attestation;

        return (_initial_length - data.length, result);
        /* solhint-enable */
    }
}

