// Code generated by MockGen. DO NOT EDIT.
// Source: message_handler.go
//
// Generated by this command:
//
//	mockgen -source=message_handler.go -destination=./mocks/mock_message_handler.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	ids "github.com/ava-labs/avalanchego/ids"
	logging "github.com/ava-labs/avalanchego/utils/logging"
	messages "github.com/ava-labs/icm-services/messages"
	aggregator "github.com/ava-labs/icm-services/signature-aggregator/aggregator"
	vms "github.com/ava-labs/icm-services/vms"
	evm "github.com/ava-labs/icm-services/vms/evm"
	common "github.com/ava-labs/libevm/common"
	gomock "go.uber.org/mock/gomock"
)

// MockMessageHandlerFactory is a mock of MessageHandlerFactory interface.
type MockMessageHandlerFactory struct {
	ctrl     *gomock.Controller
	recorder *MockMessageHandlerFactoryMockRecorder
	isgomock struct{}
}

// MockMessageHandlerFactoryMockRecorder is the mock recorder for MockMessageHandlerFactory.
type MockMessageHandlerFactoryMockRecorder struct {
	mock *MockMessageHandlerFactory
}

// NewMockMessageHandlerFactory creates a new mock instance.
func NewMockMessageHandlerFactory(ctrl *gomock.Controller) *MockMessageHandlerFactory {
	mock := &MockMessageHandlerFactory{ctrl: ctrl}
	mock.recorder = &MockMessageHandlerFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageHandlerFactory) EXPECT() *MockMessageHandlerFactoryMockRecorder {
	return m.recorder
}

// EventFilter mocks base method.
func (m *MockMessageHandlerFactory) EventFilter() evm.EventFilter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventFilter")
	ret0, _ := ret[0].(evm.EventFilter)
	return ret0
}

// EventFilter indicates an expected call of EventFilter.
func (mr *MockMessageHandlerFactoryMockRecorder) EventFilter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventFilter", reflect.TypeOf((*MockMessageHandlerFactory)(nil).EventFilter))
}

// GetMessageRoutingInfo mocks base method.
func (m *MockMessageHandlerFactory) GetMessageRoutingInfo(message *messages.SourceMessage) (messages.MessageRoutingInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageRoutingInfo", message)
	ret0, _ := ret[0].(messages.MessageRoutingInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessageRoutingInfo indicates an expected call of GetMessageRoutingInfo.
func (mr *MockMessageHandlerFactoryMockRecorder) GetMessageRoutingInfo(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageRoutingInfo", reflect.TypeOf((*MockMessageHandlerFactory)(nil).GetMessageRoutingInfo), message)
}

// NewMessageHandler mocks base method.
func (m *MockMessageHandlerFactory) NewMessageHandler(logger logging.Logger, message *messages.SourceMessage, destinationClient vms.DestinationClient, signatureAggregator *aggregator.SignatureAggregator, metrics messages.Metrics, signingSubnetID ids.ID, quorumNumerator uint64) (messages.MessageHandler, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewMessageHandler", logger, message, destinationClient, signatureAggregator, metrics, signingSubnetID, quorumNumerator)
	ret0, _ := ret[0].(messages.MessageHandler)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewMessageHandler indicates an expected call of NewMessageHandler.
func (mr *MockMessageHandlerFactoryMockRecorder) NewMessageHandler(logger, message, destinationClient, signatureAggregator, metrics, signingSubnetID, quorumNumerator any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewMessageHandler", reflect.TypeOf((*MockMessageHandlerFactory)(nil).NewMessageHandler), logger, message, destinationClient, signatureAggregator, metrics, signingSubnetID, quorumNumerator)
}

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
	isgomock struct{}
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// IncAbandonedRelayMessageCount mocks base method.
func (m *MockMetrics) IncAbandonedRelayMessageCount(failureReason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncAbandonedRelayMessageCount", failureReason)
}

// IncAbandonedRelayMessageCount indicates an expected call of IncAbandonedRelayMessageCount.
func (mr *MockMetricsMockRecorder) IncAbandonedRelayMessageCount(failureReason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncAbandonedRelayMessageCount", reflect.TypeOf((*MockMetrics)(nil).IncAbandonedRelayMessageCount), failureReason)
}

// IncFailedRelayMessageCount mocks base method.
func (m *MockMetrics) IncFailedRelayMessageCount(failureReason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncFailedRelayMessageCount", failureReason)
}

// IncFailedRelayMessageCount indicates an expected call of IncFailedRelayMessageCount.
func (mr *MockMetricsMockRecorder) IncFailedRelayMessageCount(failureReason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncFailedRelayMessageCount", reflect.TypeOf((*MockMetrics)(nil).IncFailedRelayMessageCount), failureReason)
}

// IncFetchSignatureAppRequestCount mocks base method.
func (m *MockMetrics) IncFetchSignatureAppRequestCount() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncFetchSignatureAppRequestCount")
}

// IncFetchSignatureAppRequestCount indicates an expected call of IncFetchSignatureAppRequestCount.
func (mr *MockMetricsMockRecorder) IncFetchSignatureAppRequestCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncFetchSignatureAppRequestCount", reflect.TypeOf((*MockMetrics)(nil).IncFetchSignatureAppRequestCount))
}

// IncSuccessfulRelayMessageCount mocks base method.
func (m *MockMetrics) IncSuccessfulRelayMessageCount() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncSuccessfulRelayMessageCount")
}

// IncSuccessfulRelayMessageCount indicates an expected call of IncSuccessfulRelayMessageCount.
func (mr *MockMetricsMockRecorder) IncSuccessfulRelayMessageCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncSuccessfulRelayMessageCount", reflect.TypeOf((*MockMetrics)(nil).IncSuccessfulRelayMessageCount))
}

// SetCreateSignedMessageLatencyMS mocks base method.
func (m *MockMetrics) SetCreateSignedMessageLatencyMS(latency float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCreateSignedMessageLatencyMS", latency)
}

// SetCreateSignedMessageLatencyMS indicates an expected call of SetCreateSignedMessageLatencyMS.
func (mr *MockMetricsMockRecorder) SetCreateSignedMessageLatencyMS(latency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCreateSignedMessageLatencyMS", reflect.TypeOf((*MockMetrics)(nil).SetCreateSignedMessageLatencyMS), latency)
}

// MockMessageHandler is a mock of MessageHandler interface.
type MockMessageHandler struct {
	ctrl     *gomock.Controller
	recorder *MockMessageHandlerMockRecorder
	isgomock struct{}
}

// MockMessageHandlerMockRecorder is the mock recorder for MockMessageHandler.
type MockMessageHandlerMockRecorder struct {
	mock *MockMessageHandler
}

// NewMockMessageHandler creates a new mock instance.
func NewMockMessageHandler(ctrl *gomock.Controller) *MockMessageHandler {
	mock := &MockMessageHandler{ctrl: ctrl}
	mock.recorder = &MockMessageHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageHandler) EXPECT() *MockMessageHandlerMockRecorder {
	return m.recorder
}

// ProcessMessage mocks base method.
func (m *MockMessageHandler) ProcessMessage() (common.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessMessage")
	ret0, _ := ret[0].(common.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessMessage indicates an expected call of ProcessMessage.
func (mr *MockMessageHandlerMockRecorder) ProcessMessage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessMessage", reflect.TypeOf((*MockMessageHandler)(nil).ProcessMessage))
}
