// Code generated by MockGen. DO NOT EDIT.
// Source: message_handler.go
//
// Generated by this command:
//
//	mockgen -source=message_handler.go -destination=./mocks/mock_message_handler.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	ids "github.com/ava-labs/avalanchego/ids"
	logging "github.com/ava-labs/avalanchego/utils/logging"
	warp "github.com/ava-labs/avalanchego/vms/platformvm/warp"
	messages "github.com/ava-labs/icm-services/messages"
	aggregator "github.com/ava-labs/icm-services/signature-aggregator/aggregator"
	vms "github.com/ava-labs/icm-services/vms"
	common "github.com/ava-labs/libevm/common"
	gomock "go.uber.org/mock/gomock"
)

// MockMessageHandlerFactory is a mock of MessageHandlerFactory interface.
type MockMessageHandlerFactory struct {
	ctrl     *gomock.Controller
	recorder *MockMessageHandlerFactoryMockRecorder
	isgomock struct{}
}

// MockMessageHandlerFactoryMockRecorder is the mock recorder for MockMessageHandlerFactory.
type MockMessageHandlerFactoryMockRecorder struct {
	mock *MockMessageHandlerFactory
}

// NewMockMessageHandlerFactory creates a new mock instance.
func NewMockMessageHandlerFactory(ctrl *gomock.Controller) *MockMessageHandlerFactory {
	mock := &MockMessageHandlerFactory{ctrl: ctrl}
	mock.recorder = &MockMessageHandlerFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageHandlerFactory) EXPECT() *MockMessageHandlerFactoryMockRecorder {
	return m.recorder
}

// GetMessageRoutingInfo mocks base method.
func (m *MockMessageHandlerFactory) GetMessageRoutingInfo(unsignedMessage *warp.UnsignedMessage) (messages.MessageRoutingInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageRoutingInfo", unsignedMessage)
	ret0, _ := ret[0].(messages.MessageRoutingInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessageRoutingInfo indicates an expected call of GetMessageRoutingInfo.
func (mr *MockMessageHandlerFactoryMockRecorder) GetMessageRoutingInfo(unsignedMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageRoutingInfo", reflect.TypeOf((*MockMessageHandlerFactory)(nil).GetMessageRoutingInfo), unsignedMessage)
}

// NewMessageHandler mocks base method.
func (m *MockMessageHandlerFactory) NewMessageHandler(logger logging.Logger, unsignedMessage *warp.UnsignedMessage, destinationClient vms.DestinationClient, signatureAggregator *aggregator.SignatureAggregator, metrics messages.Metrics) (messages.MessageHandler, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewMessageHandler", logger, unsignedMessage, destinationClient, signatureAggregator, metrics)
	ret0, _ := ret[0].(messages.MessageHandler)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewMessageHandler indicates an expected call of NewMessageHandler.
func (mr *MockMessageHandlerFactoryMockRecorder) NewMessageHandler(logger, unsignedMessage, destinationClient, signatureAggregator, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewMessageHandler", reflect.TypeOf((*MockMessageHandlerFactory)(nil).NewMessageHandler), logger, unsignedMessage, destinationClient, signatureAggregator, metrics)
}

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
	isgomock struct{}
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// IncFailedRelayMessageCount mocks base method.
func (m *MockMetrics) IncFailedRelayMessageCount(failureReason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncFailedRelayMessageCount", failureReason)
}

// IncFailedRelayMessageCount indicates an expected call of IncFailedRelayMessageCount.
func (mr *MockMetricsMockRecorder) IncFailedRelayMessageCount(failureReason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncFailedRelayMessageCount", reflect.TypeOf((*MockMetrics)(nil).IncFailedRelayMessageCount), failureReason)
}

// IncFetchSignatureAppRequestCount mocks base method.
func (m *MockMetrics) IncFetchSignatureAppRequestCount() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncFetchSignatureAppRequestCount")
}

// IncFetchSignatureAppRequestCount indicates an expected call of IncFetchSignatureAppRequestCount.
func (mr *MockMetricsMockRecorder) IncFetchSignatureAppRequestCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncFetchSignatureAppRequestCount", reflect.TypeOf((*MockMetrics)(nil).IncFetchSignatureAppRequestCount))
}

// IncSuccessfulRelayMessageCount mocks base method.
func (m *MockMetrics) IncSuccessfulRelayMessageCount() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncSuccessfulRelayMessageCount")
}

// IncSuccessfulRelayMessageCount indicates an expected call of IncSuccessfulRelayMessageCount.
func (mr *MockMetricsMockRecorder) IncSuccessfulRelayMessageCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncSuccessfulRelayMessageCount", reflect.TypeOf((*MockMetrics)(nil).IncSuccessfulRelayMessageCount))
}

// SetCreateSignedMessageLatencyMS mocks base method.
func (m *MockMetrics) SetCreateSignedMessageLatencyMS(latency float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCreateSignedMessageLatencyMS", latency)
}

// SetCreateSignedMessageLatencyMS indicates an expected call of SetCreateSignedMessageLatencyMS.
func (mr *MockMetricsMockRecorder) SetCreateSignedMessageLatencyMS(latency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCreateSignedMessageLatencyMS", reflect.TypeOf((*MockMetrics)(nil).SetCreateSignedMessageLatencyMS), latency)
}

// MockMessageHandler is a mock of MessageHandler interface.
type MockMessageHandler struct {
	ctrl     *gomock.Controller
	recorder *MockMessageHandlerMockRecorder
	isgomock struct{}
}

// MockMessageHandlerMockRecorder is the mock recorder for MockMessageHandler.
type MockMessageHandlerMockRecorder struct {
	mock *MockMessageHandler
}

// NewMockMessageHandler creates a new mock instance.
func NewMockMessageHandler(ctrl *gomock.Controller) *MockMessageHandler {
	mock := &MockMessageHandler{ctrl: ctrl}
	mock.recorder = &MockMessageHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageHandler) EXPECT() *MockMessageHandlerMockRecorder {
	return m.recorder
}

// GetUnsignedMessage mocks base method.
func (m *MockMessageHandler) GetUnsignedMessage() *warp.UnsignedMessage {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnsignedMessage")
	ret0, _ := ret[0].(*warp.UnsignedMessage)
	return ret0
}

// GetUnsignedMessage indicates an expected call of GetUnsignedMessage.
func (mr *MockMessageHandlerMockRecorder) GetUnsignedMessage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnsignedMessage", reflect.TypeOf((*MockMessageHandler)(nil).GetUnsignedMessage))
}

// ProcessMessage mocks base method.
func (m *MockMessageHandler) ProcessMessage(signingSubnetID ids.ID, quorumNumerator uint64) (common.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessMessage", signingSubnetID, quorumNumerator)
	ret0, _ := ret[0].(common.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessMessage indicates an expected call of ProcessMessage.
func (mr *MockMessageHandlerMockRecorder) ProcessMessage(signingSubnetID, quorumNumerator any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessMessage", reflect.TypeOf((*MockMessageHandler)(nil).ProcessMessage), signingSubnetID, quorumNumerator)
}

// SendMessage mocks base method.
func (m *MockMessageHandler) SendMessage(signedMessage *warp.Message) (common.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", signedMessage)
	ret0, _ := ret[0].(common.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockMessageHandlerMockRecorder) SendMessage(signedMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockMessageHandler)(nil).SendMessage), signedMessage)
}

// ShouldSendMessage mocks base method.
func (m *MockMessageHandler) ShouldSendMessage() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShouldSendMessage")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShouldSendMessage indicates an expected call of ShouldSendMessage.
func (mr *MockMessageHandlerMockRecorder) ShouldSendMessage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShouldSendMessage", reflect.TypeOf((*MockMessageHandler)(nil).ShouldSendMessage))
}
