// Code generated by icm-macros. DO NOT EDIT.
// Source: icm-contracts/ethereum/utils/ValidatorSets.sol
// To regenerate: ./scripts/expand_macros.sh

// (c) 2026, Ava Labs, Inc. All rights reserved.
// See the file LICENSE for licensing terms.
// SPDX-License-Identifier: LicenseRef-Ecosystem
pragma solidity ^0.8.30;

import {BLST} from "./BLST.sol";
import {Math} from "@openzeppelin/contracts@5.1.0/utils/math/Math.sol";
import {MerkleProof} from "@openzeppelin/contracts@5.1.0/utils/cryptography/MerkleProof.sol";

/**
 * THIS IS LIBRARY IS UN-AUDITED CODE.
 * DO NOT USE THIS CODE IN PRODUCTION.
 */

// #[pack(contract="ValidatorSets", visibility="internal")]
// #[unpack(contract="ValidatorSets", visibility="internal", calldata)]
struct Validator {
    // #[pack(method="BLST.unPadUncompressedBlsPublicKey")]
    // #[unpack(
    //    length=BLST.BLS_UNCOMPRESSED_PUBLIC_KEY_INPUT_LENGTH,
    //    method="BLST.padUncompressedBLSPublicKey",
    //  )]
    bytes blsPublicKey;
    uint64 weight;
}

struct ValidatorSet {
    bytes32 avalancheBlockchainID;
    Validator[] validators;
    uint64 totalWeight;
    uint64 pChainHeight;
    uint64 pChainTimestamp;
}

// The payload that initiates registering / updating a
// Validator set for the chain with ID `avalancheBlockchainID`.
// #[pack(contract="ValidatorSets", visibility="internal")]
// #[unpack(contract="ValidatorSets", visibility="internal", calldata)]
struct ValidatorSetMetadata {
    bytes32 avalancheBlockchainID;
    uint64 pChainHeight;
    uint64 pChainTimestamp;
    // A list of hashes for each shard. These are expected to arrive
    // in order
    // #[pack(length=uint32)]
    // #[unpack(length=uint32)]
    bytes32[] shardHashes;
}

// A shard to add to a validator set for which partial data has already
// been received. The `avalancheBlockchainID` field will be used to lookup the
// existing partial data
// #[pack(
//    name="serializeValidatorSetShard",
//    contract="ValidatorSets",
//    visibility="internal",
//  )]
// #[unpack(
//    name="parseValidatorSetShard",
//    contract="ValidatorSets",
//    visibility="internal",
//    calldata,
//  )]
struct ValidatorSetShard {
    // Which shard this is. These are expected to be processed in order
    uint64 shardNumber;
    // The avalanche blockchain ID whose validator set we are updating
    bytes32 avalancheBlockchainID;
}

// A partial Validator set which can be constructed from
//  shards sent across multiple transactions
struct PartialValidatorSet {
    uint64 pChainHeight;
    uint64 pChainTimestamp;
    // A list of hashes for each shard. These are expected to arrive
    // in order
    bytes32[] shardHashes;
    // The amount of shard already received
    uint64 shardsReceived;
    // The validators received so far
    Validator[] validators;
    // The weight of the above validators
    uint64 partialWeight;
    // A flag to indicate that this is now a complete validator set
    bool inProgress;
}

// #[pack(
//    name="serializeValidatorSetSignature",
//    contract="ValidatorSets",
//    visibility="internal",
//  )]
struct ValidatorSetSignature {
    // #[pack(length=drop)]
    bytes signers;
    // #[pack(length=drop)]
    bytes signature;
}

// ValidatorChange represents a single validator addition, removal, or modification
// #[pack(contract="ValidatorSets", visibility="internal")]
// #[unpack(contract="ValidatorSets", visibility="internal", calldata)]
struct ValidatorChange {
    // #[pack(method="BLST.unPadUncompressedBlsPublicKey")]
    // #[unpack(length=96, method="BLST.padUncompressedBLSPublicKey")]
    bytes blsPublicKey; // 96 bytes uncompressed
    uint64 weight; // Weight at current height (0 for removals)
}

// ValidatorSetDiff contains the diff information from a signed message
// #[pack(contract="ValidatorSets", visibility="internal")]
struct ValidatorSetDiff {
    bytes32 avalancheBlockchainID;
    // Previous state
    uint64 previousHeight;
    uint64 previousTimestamp;
    // Current state
    uint64 currentHeight;
    uint64 currentTimestamp;
    // Changes sorted by key
    // #[pack(length=uint32)]
    ValidatorChange[] changes;
    uint32 numAdded;
    // #[pack(ignore)]
    uint256 newSize;
}

/// Compact, constant size on-chain commitment to an Avalanche validator set.
// #[pack(contract="ValidatorSets", visibility="internal")]
// #[unpack(contract="ValidatorSets", visibility="internal", calldata)]
struct ValidatorSetMerkleCommitment {
    bytes32 avalancheBlockchainID;
    bytes32 root;
    uint64 totalWeight;
    uint64 pChainHeight;
    uint64 pChainTimestamp;
}

/// Attestation envelope for a BLS-signed ICM message. Contains the
/// signing validators for a specific chain, a Merkle multi-inclusion proof binding
/// them to the registry's stored root, and the aggregate BLS signature.
/// @dev The signers must be stored in increasing lexicographic order by their BLS public key.
// #[pack(contract="ValidatorSets", visibility="internal")]
// #[unpack(contract="ValidatorSets", visibility="internal", calldata)]
struct ValidatorSetMerkleAttestation {
    // #[pack(length=uint32)]
    // #[unpack(length=uint32)]
    Validator[] signers;
    // #[pack(length=uint32)]
    // #[unpack(length=uint32)]
    bytes32[] proof;
    // #[pack(method="packProofFlags")]
    // #[unpack(method="unpackProofFlags")]
    bool[] proofFlags;
    // #[pack(method="abi.encodePacked")]
    // #[unpack(default)]
    bytes aggregateBlsSig;
}

library ValidatorSets {
    /* solhint-disable no-inline-assembly */
    uint256 private constant QUORUM_NUM = 67;
    uint256 private constant QUORUM_DEN = 100;

    /*
     * @dev The number of validators is expected to fit in 4 bytes
     */
    uint256 private constant PAYLOAD_TYPE_ID_LENGTH = 4;

    /*
     * @dev The number of validators is expected to fit in 4 bytes
     */
    uint256 private constant NUM_VALIDATOR_LENGTH = 4;
    /*
     * @dev The weight of a validator is expected to fit in 8 bytes
     */
    uint256 private constant VALIDATOR_WEIGHT_LENGTH = 8;

    /*
     * @dev The (de)serialization codec prefix
     */
    bytes2 private constant CODEC = bytes2(0);

    /*
     * @dev The number of bytes in the `Validator` struct
     */
    uint256 private constant VALIDATOR_BYTES = BLST.BLS_UNCOMPRESSED_PUBLIC_KEY_INPUT_LENGTH + VALIDATOR_WEIGHT_LENGTH;

    /**
     * @dev Gas-optimized replacement of a storage array with a memory array.
     * Overwrites existing slots, then pushes or pops the difference.
     * @param oldArray The existing array in contract storage.
     * @param newArray The new array loaded in memory.
     */
    function replaceValidators(Validator[] storage oldArray, Validator[] memory newArray) internal {
        uint256 oldLen = oldArray.length;
        uint256 newLen = newArray.length;
        uint256 minLen = oldLen < newLen ? oldLen : newLen;
        uint256 i = 0;
        // Overwrite
        for (; i < minLen;) {
            oldArray[i] = newArray[i];
            unchecked {
                ++i;
            }
        }
        // Push
        if (newLen > oldLen) {
            for (; i < newLen;) {
                oldArray.push(newArray[i]);
                unchecked {
                    ++i;
                }
            }
        }
        // Pop
        else if (oldLen > newLen) {
            uint256 diffLen = oldLen - newLen;
            for (uint256 j = 0; j < diffLen;) {
                oldArray.pop();
                unchecked {
                    ++j;
                }
            }
        }
    }

    /*
     * @notice Verifies that a quorum of the input validator set produced the input signature over the input message
     */
    function verifyValidatorSetSignature(
        ValidatorSetSignature memory signature,
        bytes memory message,
        ValidatorSet memory validatorSet
    ) internal view returns (bool) {
        (bytes memory aggregateKey, uint64 aggregateWeight) =
            filterValidators(signature.signers, validatorSet.validators);
        if (!verifyWeight(aggregateWeight, validatorSet.totalWeight)) {
            return false;
        }
        return BLST.verifySignature(aggregateKey, signature.signature, message);
    }

    /**
     * @dev Selects validators by index using the signers bitset, then aggregates their BLS public keys and weights.
     * The bitset matches Go's big.Int.Bytes() (big-endian): bit i of the integer is
     * bit (i % 8) of byte signers[signers.length - 1 - i / 8].
     * @return aggregatePublicKey The aggregate BLS public key of the selected validators
     * @return aggregateWeight The sum of weights of the selected validators
     */
    function filterValidators(bytes memory signers, Validator[] memory validators)
        internal
        view
        returns (bytes memory, uint64)
    {
        bytes memory aggregatePublicKey;
        uint64 aggregateWeight = 0;
        if (validators.length == 0) {
            revert("Cannot validate against an empty list of validators");
        }

        uint256 validatorsLen = validators.length;
        uint256 signersLen = signers.length;
        for (uint256 i = 0; i < validatorsLen;) {
            uint256 byteOffset = i / 8;
            if (byteOffset >= signersLen) {
                break;
            }
            uint256 byteIdx = signersLen - 1 - byteOffset;
            uint8 bitPos = uint8(i % 8);
            if (uint8(signers[byteIdx]) & (uint8(1) << bitPos) != 0) {
                Validator memory validator = validators[i];
                if (aggregateWeight > 0) {
                    aggregatePublicKey = BLST.addG1(aggregatePublicKey, validator.blsPublicKey);
                } else {
                    aggregatePublicKey = validator.blsPublicKey;
                }
                aggregateWeight += validator.weight;
            }
            unchecked {
                ++i;
            }
        }
        return (aggregatePublicKey, aggregateWeight);
    }

    /**
     * @dev ICM message verification scheme using Merkle attestations. Includes the following steps:
     * 1. Reconstruct each signer's leaf
     * 2. Verify all leaves against the stored root via a Merkle multi-inclusion proof
     * 3. Enforce uniqueness of signers
     * 4. Perform a stake-weighted quorum threshold check
     * 5. Perform aggregate BLS signature verification
     */
    function verifyMerkleAttestation(
        bytes calldata rawAttestation,
        bytes memory signedData,
        ValidatorSetMerkleCommitment storage comm
    ) internal view returns (bool) {
        ValidatorSetMerkleAttestation memory att = ValidatorSets.parseMerkleAttestation(rawAttestation);
        uint256 numSigners = att.signers.length;
        require(numSigners > 0, "No signers");

        // Reconstruct leaves
        bytes32[] memory leaves = new bytes32[](numSigners);
        for (uint256 i = 0; i < numSigners;) {
            leaves[i] = sha256(abi.encodePacked(att.signers[i].blsPublicKey, att.signers[i].weight));
            unchecked {
                ++i;
            }
        }

        // Perform Merkle multi-inclusion proof verification against the stored root
        // TODO: Switch to multiProofVerifyCalldata once parseMerkleAttestation returns calldata slice offsets instead of a memory struct for additional gas savings
        if (!MerkleProof.multiProofVerify(att.proof, att.proofFlags, comm.root, leaves, _sha256Pair)) {
            return false;
        }

        // Stake-weighted quorum threshold check
        uint64 signerWeight = 0;
        for (uint256 i = 0; i < numSigners; ++i) {
            signerWeight += att.signers[i].weight;
        }
        if (!ValidatorSets.verifyWeight(signerWeight, comm.totalWeight)) {
            return false;
        }

        // Aggregate pubkeys and verify BLS signature over the warp preimage.
        bytes memory aggregateKey = att.signers[0].blsPublicKey;
        for (uint256 i = 1; i < numSigners; ++i) {
            aggregateKey = BLST.addG1(aggregateKey, att.signers[i].blsPublicKey);
        }
        return BLST.verifySignature(aggregateKey, att.aggregateBlsSig, signedData);
    }

    /**
     * @notice Parses the validators from a serialized validator set
     * @param data The serialized validator set. The serialized format is:
     * - 2 bytes: codec ID (0x0000)
     * - 4 bytes: number of validators
     * - 96 bytes per validator: unformatted BLS public key
     * - 8 bytes per validator: weight
     * @return validators The parsed validators
     * @return totalWeight The total weight of all validators
     */
    function parseValidators(bytes calldata data) internal pure returns (Validator[] memory, uint64) {
        // Check the codec ID is 0
        require(data[0] == 0 && data[1] == 0, "Invalid codec ID");

        // Parse the number of validators
        uint32 numValidators = uint32(bytes4(data[2:2 + NUM_VALIDATOR_LENGTH]));

        // Parse the validators
        Validator[] memory validators = new Validator[](numValidators);
        uint64 totalWeight = 0;
        // The position in the bytes were are currently parsing
        uint256 currentPosition = 6;
        // we will require that public keys appear in increasing order,
        // lexicographically sorted as bytes
        bytes memory previousPublicKey = new bytes(BLST.BLS_UNCOMPRESSED_PUBLIC_KEY_INPUT_LENGTH);

        for (uint32 i = 0; i < numValidators; i++) {
            bytes memory unformattedPublicKey =
                data[currentPosition:currentPosition + BLST.BLS_UNCOMPRESSED_PUBLIC_KEY_INPUT_LENGTH];
            require(
                BLST.comparePublicKeys(unformattedPublicKey, previousPublicKey) > 0,
                "BLS public key must be greater than the latest public key"
            );
            // A serialized validator consists of
            // VALIDATOR_BYTES = BLST.BLS_UNCOMPRESSED_PUBLIC_KEY_INPUT_LENGTH + VALIDATOR_WEIGHT_LENGTH
            // bytes. To get the the weight, we skip the first  BLST.BLS_UNCOMPRESSED_PUBLIC_KEY_INPUT_LENGTH
            // bytes up to VALIDATOR_BYTES from the current byte position.
            uint64 weight = uint64(
                bytes8(
                    data[currentPosition
                            + BLST.BLS_UNCOMPRESSED_PUBLIC_KEY_INPUT_LENGTH:currentPosition + VALIDATOR_BYTES
                    ]
                )
            );
            require(weight > 0, "Validator weight must be greater than 0");
            validators[i] =
                Validator({blsPublicKey: BLST.padUncompressedBLSPublicKey(unformattedPublicKey), weight: weight});
            previousPublicKey = unformattedPublicKey;
            totalWeight += weight;
            // move the current position past the bytes of this validator
            currentPosition += VALIDATOR_BYTES;
        }
        return (validators, totalWeight);
    }

    function serializeValidators(Validator[] memory validators) internal pure returns (bytes memory) {
        bytes memory serialized = new bytes(2 + 4);

        assembly ("memory-safe") {
            let validator_length := mload(validators)
            //encode the number of validators
            // convert bytes32 to bytes4 and store the length
            mstore(add(serialized, 0x22), shl(224, validator_length))
        }

        // encode the validators
        for (uint256 i = 0; i < validators.length; i++) {
            serialized = abi.encodePacked(serialized, packValidator(validators[i]));
        }
        return serialized;
    }

    /*
    * @dev Serializes a ValidatorSetMerkleAttestation in the format expected by parseMerkleAttestation.
    */
    function serializeMerkleAttestation(ValidatorSetMerkleAttestation memory att) internal pure returns (bytes memory) {
        return abi.encodePacked(CODEC, packValidatorSetMerkleAttestation(att));
    }

    /**
     * @notice Deserialize a bit set back into an array of bools.
     * @dev Inverse of packProofFlags. Reads a uint32 count then ceil(count/8) packed bytes.
     * @return consumed Number of bytes read from data.
     * @return flags The decoded bool array.
     */
    function unpackProofFlags(bytes calldata data) internal pure returns (uint256, bool[] memory) {
        uint32 numFlags = uint32(bytes4(data[0:4]));
        uint256 flagBytesLen = Math.ceilDiv(numFlags, 8);
        bool[] memory flags = new bool[](numFlags);
        for (uint256 i = 0; i < numFlags;) {
            uint8 byteVal = uint8(data[4 + (i >> 3)]);
            flags[i] = (byteVal >> uint8(i & 7)) & 1 == 1;
            unchecked {
                ++i;
            }
        }
        return (4 + flagBytesLen, flags);
    }

    /**
     * @notice serialize an array of bools to a bit set
     */
    function packProofFlags(bool[] memory flags) internal pure returns (bytes memory) {
        uint32 numFlags = uint32(flags.length);
        uint256 flagBytesLen = Math.ceilDiv(numFlags, 8);
        bytes memory packedFlags = new bytes(flagBytesLen);
        for (uint256 i = 0; i < numFlags; i++) {
            if (flags[i]) {
                packedFlags[i >> 3] |= bytes1(uint8(1) << uint8(i & 7));
            }
        }
        return abi.encodePacked(numFlags, packedFlags);
    }

    /**
     * @notice Serializes a ValidatorSetMerkleCommitment payload.
     */
    function serializeMerkleCommitment(ValidatorSetMerkleCommitment memory commitment)
        internal
        pure
        returns (bytes memory)
    {
        bytes4 payloadType = bytes4(0x00000006);
        return abi.encodePacked(CODEC, payloadType, packValidatorSetMerkleCommitment(commitment));
    }

    /**
     * @notice Deserializes the validator state payload
     * @param data The serialized validator state payload. The serialized format is:
     * - 2 bytes: codec ID (0x0000)
     * - 4 bytes: payload type id
     * - 32 bytes: Avalanche blockchain ID
     * - 8 bytes: Avalanche P-chain height
     * - 8 bytes: Avalanche P-chain timestamp
     * - the remainder is an abi-encoded array of hashes
     * @return ValidatorSetStatePayload instance
     */
    function parseValidatorSetMetadata(bytes calldata data) internal pure returns (ValidatorSetMetadata memory) {
        // Check the codec ID is 0
        require(data[0] == 0 && data[1] == 0, "Invalid codec ID");

        // Parse the payload type ID, and confirm it is 4 for ValidatorSetState
        uint32 payloadTypeID = uint32(bytes4(data[2:2 + PAYLOAD_TYPE_ID_LENGTH]));
        require(payloadTypeID == PAYLOAD_TYPE_ID_LENGTH, "Invalid ValidatorSetState payload type ID");
        (, ValidatorSetMetadata memory result) = unpackValidatorSetMetadata(data[2 + PAYLOAD_TYPE_ID_LENGTH:]);
        return result;
    }

    /**
     * @notice Parses a ValidatorSetDiff payload from serialized bytes
     * @dev The payload type ID must be 5 for ValidatorSetDiff
     * @param data The serialized ValidatorSetDiff payload
     * @return diff The parsed ValidatorSetDiff
     */
    function parseValidatorSetDiff(bytes calldata data, uint256 currentValidatorCount)
        internal
        pure
        returns (ValidatorSetDiff memory diff)
    {
        {
            require(data[0] == 0 && data[1] == 0, "Invalid codec ID");
            uint32 payloadTypeID = uint32(bytes4(data[2:6]));
            require(payloadTypeID == 5, "Invalid ValidatorSetDiff payload type ID");
        }
        uint256 offset = 6;
        diff.avalancheBlockchainID = bytes32(data[offset:offset + 32]);
        offset += 32;
        // Previous State
        {
            diff.previousHeight = uint64(bytes8(data[offset:offset + 8]));
            offset += 8;
            diff.previousTimestamp = uint64(bytes8(data[offset:offset + 8]));
            offset += 8;
        }

        // Current State
        {
            diff.currentHeight = uint64(bytes8(data[offset:offset + 8]));
            offset += 8;
            diff.currentTimestamp = uint64(bytes8(data[offset:offset + 8]));
            offset += 8;
        }
        // Validator Changes
        {
            uint32 numChanges = uint32(bytes4(data[offset:offset + 4]));
            offset += 4;
            diff.changes = new ValidatorChange[](numChanges);
            uint256 numRemoved = 0;
            for (uint32 i = 0; i < numChanges;) {
                (diff.changes[i], offset) = parseValidatorChange(data, offset);
                if (diff.changes[i].weight == 0) {
                    unchecked {
                        ++numRemoved;
                    }
                }
                unchecked {
                    ++i;
                }
            }
            diff.numAdded = uint32(bytes4(data[offset:offset + 4]));
            offset += 4;
            diff.newSize = currentValidatorCount + diff.numAdded - numRemoved;
        }
        return diff;
    }

    /**
     * @notice Parses a single ValidatorChange from serialized bytes
     * @param data The serialized data
     * @param offset The offset to start parsing from
     * @return change The parsed ValidatorChange
     * @return newOffset The new offset after parsing
     */
    function parseValidatorChange(bytes calldata data, uint256 offset)
        internal
        pure
        returns (ValidatorChange memory, uint256)
    {
        (uint256 read, ValidatorChange memory change) = unpackValidatorChange(data[offset:]);
        return (change, offset + read);
    }

    /**
     * @notice Parses a ValidatorSetMerkleAttestation from serialized bytes
     * @param data The serialized attestation
     * @return att The parsed ValidatorSetMerkleAttestation
     */
    function parseMerkleAttestation(bytes calldata data)
        internal
        pure
        returns (ValidatorSetMerkleAttestation memory att)
    {
        require(data[0] == 0 && data[1] == 0, "Invalid codec ID");
        uint256 consumed;
        (consumed, att) = unpackValidatorSetMerkleAttestation(data[2:]);
        att.aggregateBlsSig = data[2 + consumed:2 + consumed + BLST.BLS_SIGNATURE_LENGTH];
        require(2 + consumed + BLST.BLS_SIGNATURE_LENGTH == data.length, "Trailing bytes in attestation");
        return att;
    }

    /**
     * @notice Parses a ValidatorSetMerkleCommitment payload from serialized bytes.
     * @dev The serialized format is:
     * - 2 bytes:  codec ID
     * - 4 bytes:  payload type ID
     * - 32 bytes: Avalanche blockchain ID
     * - 32 bytes: Merkle root over the validator set
     * - 8 bytes:  total validator weight
     * - 8 bytes:  P-chain height
     * - 8 bytes:  P-chain timestamp
     */
    function parseMerkleCommitment(bytes calldata data) internal pure returns (ValidatorSetMerkleCommitment memory) {
        require(data[0] == 0 && data[1] == 0, "Invalid codec ID");
        uint32 payloadTypeID = uint32(bytes4(data[2:6]));
        require(payloadTypeID == 6, "Invalid ValidatorSetMerkleCommitment payload type ID");
        (, ValidatorSetMerkleCommitment memory result) = unpackValidatorSetMerkleCommitment(data[6:]);
        return result;
    }

    /**
     * @notice Applies a presorted diff to a presorted validator array in O(N+M) time.
     * @param currentValSet The existing validators (must be sorted by BLS public key).
     * @param diff The diff containing the changes and newSize (must be sorted by BLS public key).
     * @return modified The updated validator array.
     * @return newTotalWeight The total weight of the new set.
     */
    function applyValidatorSetDiff(Validator[] memory currentValSet, ValidatorSetDiff memory diff)
        internal
        pure
        returns (Validator[] memory, uint64)
    {
        uint64 newTotalWeight = 0;
        uint256 newSize = diff.newSize;
        Validator[] memory modified = new Validator[](newSize);
        uint256 valSetPos = 0;
        uint256 changePos = 0;

        _verifySortedValidatorChanges(diff.changes);

        for (uint256 i = 0; i < newSize;) {
            int256 compare;
            ValidatorChange memory nextChange;
            Validator memory nextVal;

            // Safety checks
            if (changePos >= diff.changes.length) {
                // case 1: we've exhausted the changes, so we just take the remaining validators
                nextVal = currentValSet[valSetPos];
                compare = -1;
            } else if (valSetPos >= currentValSet.length) {
                // case 2: we've exhausted the current validator set, so we just take the remaining changes (which must all be additions)
                nextChange = diff.changes[changePos];
                compare = 1;
            } else {
                // case 3: we have both validators and changes left, so we compare the next validator and next change
                nextVal = currentValSet[valSetPos];
                nextChange = diff.changes[changePos];
                compare = BLST.comparePublicKeys(
                    BLST.unPadUncompressedBlsPublicKey(nextVal.blsPublicKey),
                    BLST.unPadUncompressedBlsPublicKey(nextChange.blsPublicKey)
                );
            }

            // Compare
            if (compare < 0) {
                // case 1: the next change occurs after this validator
                modified[i] = nextVal;
                newTotalWeight += nextVal.weight;
                valSetPos++;
                unchecked {
                    ++i;
                }
            } else if (compare > 0) {
                // case 2. this is a new validator
                modified[i] = Validator({blsPublicKey: nextChange.blsPublicKey, weight: nextChange.weight});
                newTotalWeight += nextChange.weight;
                changePos++;
                unchecked {
                    ++i;
                }
            } else {
                // case 3. this is a change to an existing validator
                // If the next weight is zero, skip
                if (nextChange.weight != 0) {
                    nextVal.weight = nextChange.weight;
                    modified[i] = nextVal;
                    newTotalWeight += nextChange.weight;
                    unchecked {
                        ++i;
                    }
                }
                changePos++;
                valSetPos++;
            }
        }
        require(modified[newSize - 1].weight > 0, "Incorrect size given in diff");
        return (modified, newTotalWeight);
    }

    /*
     * @notice Serialize a ValidatorSetStatePayload
     */
    function serializeValidatorSetMetadata(ValidatorSetMetadata memory payload) internal pure returns (bytes memory) {
        bytes4 payloadType = bytes4(0x00000004);
        return abi.encodePacked(CODEC, payloadType, packValidatorSetMetadata(payload));
    }

    /*
     * @notice Serialize a ValidatorSetDiff
     */
    function serializeValidatorSetDiff(ValidatorSetDiff memory diff) internal pure returns (bytes memory) {
        bytes4 payloadType = bytes4(0x00000005);
        return abi.encodePacked(CODEC, payloadType, packValidatorSetDiff(diff));
    }

    /*
     * @notice Deserialize bytes into `ValidatorSetSignature`
     */
    function parseValidatorSetSignature(bytes calldata signatureBytes)
        internal
        pure
        returns (ValidatorSetSignature memory)
    {
        bytes memory signers = signatureBytes[0:signatureBytes.length - BLST.BLS_SIGNATURE_LENGTH];
        bytes memory signature = signatureBytes[signatureBytes.length - BLST.BLS_SIGNATURE_LENGTH:];
        return ValidatorSetSignature({signers: signers, signature: signature});
    }

    /*
     * @notice Verifies that quorumNum * totalWeight <= quorumDen * signatureWeight
     */
    function verifyWeight(uint64 signatureWeight, uint64 totalWeight) internal pure returns (bool) {
        uint256 scaledTotalWeight = QUORUM_NUM * uint256(totalWeight);
        uint256 scaledSignatureWeight = QUORUM_DEN * uint256(signatureWeight);
        return scaledTotalWeight <= scaledSignatureWeight;
    }

    /**
     * @notice Verifies that the validator changes are sorted by public key in increasing order.
     * @dev Operates in O(n) time. Reverts if the array is not sorted.
     * @param changes The array of validator changes to verify.
     */
    function _verifySortedValidatorChanges(ValidatorChange[] memory changes) internal pure {
        uint256 len = changes.length;
        if (len < 2) return;
        for (uint256 i = 0; i < len - 1;) {
            // Compare
            int256 compare = BLST.comparePublicKeys(
                BLST.unPadUncompressedBlsPublicKey(changes[i].blsPublicKey),
                BLST.unPadUncompressedBlsPublicKey(changes[i + 1].blsPublicKey)
            );
            require(compare <= 0, "Validator changes not sorted by public key");
            unchecked {
                ++i;
            }
        }
    }

    /**
     * @dev Reconstructs the unsigned Warp message bytes that validators sign for ICM addressed-call payloads.
     * If senderAddress is address(0), the sender field is omitted from the AddressedCall encoding — this is
     * the case for validator set update messages, which carry no sender address.
     * If senderAddress is non-zero (e.g. address(this) for ICM messages sent by a contract), the
     * warp precompile sets msg.sender as the source address and it must be included in the reconstruction.
     *
     * Layout without sender: warpCodec(2) | networkID(4) | sourceChainID(32) | payloadFieldLen(4)
     *                        | addressedCallCodec(2) | typeID(4) | srcAddrLen(4)=0 | innerPayloadLen(4) | payload
     * Layout with sender:    warpCodec(2) | networkID(4) | sourceChainID(32) | payloadFieldLen(4)
     *                        | addressedCallCodec(2) | typeID(4) | srcAddrLen(4)=20 | srcAddr(20) | innerPayloadLen(4) | payload
     */
    function buildUnsignedWarpMessage(
        uint32 networkID,
        bytes32 sourceBlockchainID,
        address senderAddress,
        bytes memory payload
    ) internal pure returns (bytes memory) {
        if (senderAddress == address(0)) {
            return abi.encodePacked(
                bytes2(0),
                networkID,
                sourceBlockchainID,
                uint32(payload.length + 14),
                bytes2(0),
                uint32(1),
                uint32(0),
                uint32(payload.length),
                payload
            );
        }
        return abi.encodePacked(
            bytes2(0),
            networkID,
            sourceBlockchainID,
            uint32(payload.length + 34),
            bytes2(0),
            uint32(1),
            uint32(20),
            bytes20(senderAddress),
            uint32(payload.length),
            payload
        );
    }

    function _sha256Pair(bytes32 a, bytes32 b) internal pure returns (bytes32) {
        return a < b ? sha256(abi.encodePacked(a, b)) : sha256(abi.encodePacked(b, a));
    }

    function packValidator(Validator memory obj) internal pure returns (bytes memory) {
        /* solhint-disable */

        return abi.encodePacked(BLST.unPadUncompressedBlsPublicKey(obj.blsPublicKey), abi.encodePacked(obj.weight));
        /* solhint-enable */
    }

    function packValidatorSetMetadata(ValidatorSetMetadata memory obj) internal pure returns (bytes memory) {
        /* solhint-disable */
        bytes memory shardHashes_bytes;
        shardHashes_bytes = abi.encodePacked(uint32(obj.shardHashes.length));
        for (uint256 i_0 = 0; i_0 < obj.shardHashes.length;) {
            bytes memory shardHashes_1_bytes;
            shardHashes_1_bytes = abi.encodePacked(obj.shardHashes[i_0]);
            shardHashes_bytes = abi.encodePacked(shardHashes_bytes, shardHashes_1_bytes);
            unchecked {
                ++i_0;
            }
        }
        return abi.encodePacked(
            abi.encodePacked(obj.avalancheBlockchainID),
            abi.encodePacked(obj.pChainHeight),
            abi.encodePacked(obj.pChainTimestamp),
            shardHashes_bytes
        );
        /* solhint-enable */
    }

    function serializeValidatorSetShard(ValidatorSetShard memory obj) internal pure returns (bytes memory) {
        /* solhint-disable */

        return abi.encodePacked(abi.encodePacked(obj.shardNumber), abi.encodePacked(obj.avalancheBlockchainID));
        /* solhint-enable */
    }

    function serializeValidatorSetSignature(ValidatorSetSignature memory obj) internal pure returns (bytes memory) {
        /* solhint-disable */

        return abi.encodePacked(abi.encodePacked(obj.signers), abi.encodePacked(obj.signature));
        /* solhint-enable */
    }

    function packValidatorChange(ValidatorChange memory obj) internal pure returns (bytes memory) {
        /* solhint-disable */

        return abi.encodePacked(BLST.unPadUncompressedBlsPublicKey(obj.blsPublicKey), abi.encodePacked(obj.weight));
        /* solhint-enable */
    }

    function packValidatorSetDiff(ValidatorSetDiff memory obj) internal pure returns (bytes memory) {
        /* solhint-disable */
        bytes memory changes_bytes;
        changes_bytes = abi.encodePacked(uint32(obj.changes.length));
        for (uint256 i_0 = 0; i_0 < obj.changes.length;) {
            bytes memory changes_1_bytes;
            changes_1_bytes = packValidatorChange(obj.changes[i_0]);
            changes_bytes = abi.encodePacked(changes_bytes, changes_1_bytes);
            unchecked {
                ++i_0;
            }
        }
        return abi.encodePacked(
            abi.encodePacked(obj.avalancheBlockchainID),
            abi.encodePacked(obj.previousHeight),
            abi.encodePacked(obj.previousTimestamp),
            abi.encodePacked(obj.currentHeight),
            abi.encodePacked(obj.currentTimestamp),
            changes_bytes,
            abi.encodePacked(obj.numAdded)
        );
        /* solhint-enable */
    }

    function packValidatorSetMerkleCommitment(ValidatorSetMerkleCommitment memory obj)
        internal
        pure
        returns (bytes memory)
    {
        /* solhint-disable */

        return abi.encodePacked(
            abi.encodePacked(obj.avalancheBlockchainID),
            abi.encodePacked(obj.root),
            abi.encodePacked(obj.totalWeight),
            abi.encodePacked(obj.pChainHeight),
            abi.encodePacked(obj.pChainTimestamp)
        );
        /* solhint-enable */
    }

    function packValidatorSetMerkleAttestation(ValidatorSetMerkleAttestation memory obj)
        internal
        pure
        returns (bytes memory)
    {
        /* solhint-disable */
        bytes memory signers_bytes;
        bytes memory proof_bytes;
        signers_bytes = abi.encodePacked(uint32(obj.signers.length));
        for (uint256 i_0 = 0; i_0 < obj.signers.length;) {
            bytes memory signers_1_bytes;
            signers_1_bytes = packValidator(obj.signers[i_0]);
            signers_bytes = abi.encodePacked(signers_bytes, signers_1_bytes);
            unchecked {
                ++i_0;
            }
        }
        proof_bytes = abi.encodePacked(uint32(obj.proof.length));
        for (uint256 i_0 = 0; i_0 < obj.proof.length;) {
            bytes memory proof_1_bytes;
            proof_1_bytes = abi.encodePacked(obj.proof[i_0]);
            proof_bytes = abi.encodePacked(proof_bytes, proof_1_bytes);
            unchecked {
                ++i_0;
            }
        }
        return abi.encodePacked(
            signers_bytes, proof_bytes, packProofFlags(obj.proofFlags), abi.encodePacked(obj.aggregateBlsSig)
        );
        /* solhint-enable */
    }

    function unpackValidator(bytes calldata data) internal pure returns (uint256, Validator memory) {
        /* solhint-disable */
        uint256 _initial_length = data.length;
        Validator memory result;

        bytes memory blsPublicKey;
        {
            blsPublicKey = BLST.padUncompressedBLSPublicKey(data[0:BLST.BLS_UNCOMPRESSED_PUBLIC_KEY_INPUT_LENGTH]);
            data = data[BLST.BLS_UNCOMPRESSED_PUBLIC_KEY_INPUT_LENGTH:];
        }
        result.blsPublicKey = blsPublicKey;
        uint64 weight = uint64(bytes8(data[0:8]));
        data = data[8:];
        result.weight = weight;

        return (_initial_length - data.length, result);
        /* solhint-enable */
    }

    function unpackValidatorSetMetadata(bytes calldata data)
        internal
        pure
        returns (uint256, ValidatorSetMetadata memory)
    {
        /* solhint-disable */
        uint256 _initial_length = data.length;
        ValidatorSetMetadata memory result;

        bytes32 avalancheBlockchainID = bytes32(data[0:32]);
        data = data[32:];
        result.avalancheBlockchainID = avalancheBlockchainID;
        uint64 pChainHeight = uint64(bytes8(data[0:8]));
        data = data[8:];
        result.pChainHeight = pChainHeight;
        uint64 pChainTimestamp = uint64(bytes8(data[0:8]));
        data = data[8:];
        result.pChainTimestamp = pChainTimestamp;
        bytes32[] memory shardHashes;
        {
            uint256 length = uint256(uint32(bytes4(data[0:4])));
            data = data[4:];
            shardHashes = new bytes32[](length);
            for (uint256 i = 0; i < length;) {
                bytes32 shardHashes_1 = bytes32(data[0:32]);
                data = data[32:];
                shardHashes[i] = shardHashes_1;
                unchecked {
                    ++i;
                }
            }
        }
        result.shardHashes = shardHashes;

        return (_initial_length - data.length, result);
        /* solhint-enable */
    }

    function parseValidatorSetShard(bytes calldata data) internal pure returns (uint256, ValidatorSetShard memory) {
        /* solhint-disable */
        uint256 _initial_length = data.length;
        ValidatorSetShard memory result;

        uint64 shardNumber = uint64(bytes8(data[0:8]));
        data = data[8:];
        result.shardNumber = shardNumber;
        bytes32 avalancheBlockchainID = bytes32(data[0:32]);
        data = data[32:];
        result.avalancheBlockchainID = avalancheBlockchainID;

        return (_initial_length - data.length, result);
        /* solhint-enable */
    }

    function unpackValidatorChange(bytes calldata data) internal pure returns (uint256, ValidatorChange memory) {
        /* solhint-disable */
        uint256 _initial_length = data.length;
        ValidatorChange memory result;

        bytes memory blsPublicKey;
        {
            blsPublicKey = BLST.padUncompressedBLSPublicKey(data[0:96]);
            data = data[96:];
        }
        result.blsPublicKey = blsPublicKey;
        uint64 weight = uint64(bytes8(data[0:8]));
        data = data[8:];
        result.weight = weight;

        return (_initial_length - data.length, result);
        /* solhint-enable */
    }

    function unpackValidatorSetMerkleCommitment(bytes calldata data)
        internal
        pure
        returns (uint256, ValidatorSetMerkleCommitment memory)
    {
        /* solhint-disable */
        uint256 _initial_length = data.length;
        ValidatorSetMerkleCommitment memory result;

        bytes32 avalancheBlockchainID = bytes32(data[0:32]);
        data = data[32:];
        result.avalancheBlockchainID = avalancheBlockchainID;
        bytes32 root = bytes32(data[0:32]);
        data = data[32:];
        result.root = root;
        uint64 totalWeight = uint64(bytes8(data[0:8]));
        data = data[8:];
        result.totalWeight = totalWeight;
        uint64 pChainHeight = uint64(bytes8(data[0:8]));
        data = data[8:];
        result.pChainHeight = pChainHeight;
        uint64 pChainTimestamp = uint64(bytes8(data[0:8]));
        data = data[8:];
        result.pChainTimestamp = pChainTimestamp;

        return (_initial_length - data.length, result);
        /* solhint-enable */
    }

    function unpackValidatorSetMerkleAttestation(bytes calldata data)
        internal
        pure
        returns (uint256, ValidatorSetMerkleAttestation memory)
    {
        /* solhint-disable */
        uint256 _initial_length = data.length;
        ValidatorSetMerkleAttestation memory result;

        Validator[] memory signers;
        {
            uint256 length = uint256(uint32(bytes4(data[0:4])));
            data = data[4:];
            signers = new Validator[](length);
            for (uint256 i = 0; i < length;) {
                Validator memory signers_1;
                {
                    uint256 read;
                    (read, signers_1) = unpackValidator(data);
                    data = data[read:];
                }
                signers[i] = signers_1;
                unchecked {
                    ++i;
                }
            }
        }
        result.signers = signers;
        bytes32[] memory proof;
        {
            uint256 length = uint256(uint32(bytes4(data[0:4])));
            data = data[4:];
            proof = new bytes32[](length);
            for (uint256 i = 0; i < length;) {
                bytes32 proof_1 = bytes32(data[0:32]);
                data = data[32:];
                proof[i] = proof_1;
                unchecked {
                    ++i;
                }
            }
        }
        result.proof = proof;
        bool[] memory proofFlags;
        {
            uint256 read;
            (read, proofFlags) = unpackProofFlags(data);
            data = data[read:];
        }
        result.proofFlags = proofFlags;

        return (_initial_length - data.length, result);
        /* solhint-enable */
    }
}

