#!/usr/bin/env bash
# Copyright (C) 2023, Ava Labs, Inc. All rights reserved.
# See the file LICENSE for licensing terms.

# Expands Solidity macro annotations and writes the results to icm-contracts-expanded/.
# Only files containing #[pack] or #[unpack] annotations are written.
# Run this script whenever macro-annotated source contracts change.

set -eo pipefail

REPO_PATH=$(
    cd "$(dirname "${BASH_SOURCE[0]}")"
    cd .. && pwd
)

EXPANDED_DIR="$REPO_PATH/icm-contracts-expanded"

if ! command -v reforge &>/dev/null; then
    echo "reforge not found. Run $REPO_PATH/scripts/build_reforge.sh to install." >&2
    exit 1
fi

rm -rf "$EXPANDED_DIR"
mkdir -p "$EXPANDED_DIR"

# Write the expanded content in tmp_file to EXPANDED_DIR if the original source
# file (at $REPO_PATH/$source_path) has macro annotations.
function flush_expanded_file() {
    local source_path="$1"
    local tmp_file="$2"
    if [[ -z "$source_path" ]]; then return; fi

    local src="$REPO_PATH/$source_path"
    if [[ -f "$src" ]] && grep -qE '#\[pack|#\[unpack' "$src" 2>/dev/null; then
        # Strip the leading "icm-contracts/" prefix so that the expanded directory
        # mirrors the internal structure of icm-contracts/ without repeating it.
        local rel_path="${source_path#icm-contracts/}"
        local target="$EXPANDED_DIR/$rel_path"
        mkdir -p "$(dirname "$target")"
        {
            printf '// Code generated by icm-macros. DO NOT EDIT.\n'
            printf '// Source: %s\n' "$source_path"
            printf '// To regenerate: ./scripts/expand_macros.sh\n\n'
            cat "$tmp_file"
        } >"$target"
        echo "  Wrote: $rel_path"
    fi
}

# Expand all .sol files in a foundry profile, flushing macro-annotated files to
# EXPANDED_DIR.  The reforge --display flag emits blocks of the form:
#
#   === <repo-relative-path> ===
#   <expanded file content>
#
function expand_profile() {
    local profile="$1"
    local current_file=""
    local tmp_file
    tmp_file=$(mktemp)
    trap 'rm -f "$tmp_file"' RETURN

    echo "Expanding profile: $profile"

    while IFS= read -r line; do
        if [[ "$line" =~ ^===\ (.+)\ ===$ ]]; then
            flush_expanded_file "$current_file" "$tmp_file"
            current_file="${BASH_REMATCH[1]}"
            : >"$tmp_file"
        elif [[ -n "$current_file" ]]; then
            printf '%s\n' "$line" >>"$tmp_file"
        fi
    done < <(FOUNDRY_PROFILE="$profile" reforge --display '**/*.sol' build 2>/dev/null)

    # Flush the final file in the stream.
    flush_expanded_file "$current_file" "$tmp_file"
}

cd "$REPO_PATH"
expand_profile "default"
expand_profile "common"
expand_profile "ethereum"

echo ""
echo "Macro expansion complete. Files written to: icm-contracts-expanded/"